### Creating numpy arrays

In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
# 2D and 3D 
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

c=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(c)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=complex)
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [12]:
# np.arange
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [16]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.random.random((4,2))

array([[0.69173798, 0.3421845 ],
       [0.32926233, 0.18168571],
       [0.79747364, 0.87383975],
       [0.45358975, 0.06723614]])

In [27]:
# np.linspace
np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [30]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
# ndim
a3.ndim

3

In [ ]:
# shape
a3.shape
a2.shape

(3, 4)

In [35]:
# size 
a3.size

8

In [36]:
# itemsize
a1.itemsize

8

In [37]:
a2.itemsize

8

In [38]:
print(a2.dtype)
print(a3.dtype)

float64
int64


### Changing Datatype

In [39]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [41]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [42]:
# scalar operations:
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
# Vector operations:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [49]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[99.,  0., 76.],
       [26., 69.,  9.],
       [ 9., 68., 49.]])

In [51]:
# min / max
np.max(a1)
np.min(a1)

np.float64(0.0)

In [53]:
#sum / prod
np.sum(a1)
np.prod(a2)

np.float64(4295724668928000.0)

In [54]:
#0-> column and 1->row
np.max(a1,axis=1)

array([99., 69., 68.])

In [56]:
np.sum(a1,axis=1)

array([175., 104., 126.])

In [60]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

45.0
49.0
33.29330930449006
1108.4444444444443


In [ ]:
# trigonometric functions
np.sin(a1)

array([[-0.99920683,  0.        ,  0.56610764],
       [ 0.76255845, -0.11478481,  0.41211849],
       [ 0.41211849, -0.89792768, -0.95375265]])

In [63]:
# dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [64]:
# log and exponents 
np.log(a1)

/tmp/ipykernel_18860/1405112220.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [65]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [67]:
np.round(np.random.random((2,3))*100)

array([[49., 82., 15.],
       [13.,  8., 35.]])

In [68]:
np.floor(np.random.random((2,3))*100)

array([[25., 40., 67.],
       [15., 67.,  8.]])

In [69]:
np.ceil(np.random.random((2,3))*100)

array([[74., 43., 46.],
       [87., 91., 42.]])